### ISSUE TITLE
PHP warnings of improper function arguments

### ISSUE THREAD

**Issue by creideiki** [GregThib/ttrss-tumblr-gdpr#1]
Every time the daemon tries to update a feed (whether Tumblr or not), I get the following warnings in the daemon log:
```
[09:40:10/22349] Base feed: xxxxxxxxx
[09:40:10/22349]  => 2018-05-22 09:09:45.301243, 52 2
PHP Warning:  array_map(): Argument #2 should be an array in /var/www/localhost/htdocs/tt-rss/plugins.local/af_tumblr_gdpr/init.php on line 30
PHP Warning:  implode(): Invalid arguments passed in /var/www/localhost/htdocs/tt-rss/plugins.local/af_tumblr_gdpr/init.php on line 31
[09:40:11/22349]     1.3716 (sec)
```
The web UI reports the following update error for each such feed:
```
LibXML error 68 at line 21 (column 29): xmlParseEntityRef: no name 
```

**Comment by kierun** [comment]
I just tried it and got this:

```
/usr/bin/php /home/XXX/html/www.XXX.org/public/tt-rss/update.php --feeds --feedbrowser  --force-update
[…]
[10:25:23/10832] Base feed: http://tormentrpg.tumblr.com/rss                    
[10:25:23/10832]  => 1970-01-01 00:00:00, 73 2                                  
[10:25:40/10832]     16.6821 (sec)  
```

Your `LibXML error 68` is what I see when the plugin is not enabled.

**Comment by creideiki** [comment]
It's been a while since I pulled TT-RSS, so I just updated to latest `master`. I still get the same error.

What version of PHP are you running? I'm on 7.1.16.

**Comment by kierun** [comment]
How odd…

```
php --version
PHP 7.2.5-1+ubuntu14.04.1+deb.sury.org+1 (cli) (built: May  5 2018 06:17:01) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.5-1+ubuntu14.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies   
```

**Comment by GregThib** [comment]
Hi,
array_map() and implode() failed errors are corrected. [Two lines changed](https://github.com/GregThib/ttrss-tumblr-gdpr/commit/13d3c50e1e0d8b8e9016a2c004f94c543a543561#diff-423aaee8360d34e70158551f1e9bedaa).

@creideiki  : after a pull, could you say me if you still encounter thebug ?
Are you sure to have the curl library inside your PHP installation ?

**Comment by GregThib** [comment]
And, by the way, I confirm the @kierun statement : The error you shown about LibXML is a parse error, meaning the GDPR plugin doesn't work for you.
`LibXML error 68 at line 21 (column 29): xmlParseEntityRef: no name `

**Comment by creideiki** [comment]
After pulling the changes @GregThib mentioned above, I no longer see either error. I don't see any new posts either, but that may just be because nobody has posted yet. I'll wait a day and see.

**Comment by creideiki** [comment]
And yes, I do have cURL on the server and enabled in PHP.

**Comment by virgoparna** [comment]
When  MAX_DOWNLOAD_FILE_SIZE is not defined, then this plugin does not work currently because of CURLOPT_PROGRESSFUNCTION

**Comment by virgoparna** [comment]
Original function assigned to it had: 
return ($downloaded > MAX_DOWNLOAD_FILE_SIZE) ? 1 : 0; // if max size is set, abort when exceeding it
changed it to:
if (defined("MAX_DOWNLOAD_FILE_SIZE")) {
                                return ($downloaded > MAX_DOWNLOAD_FILE_SIZE) ? 1 : 0; // if max size is set, abort when exceeding it
                        }
                        else
                                return 0;
and it now works.

**Comment by creideiki** [comment]
This seems to work now.
