### ISSUE TITLE
Call to undefined function _debug_suppress()

### ISSUE THREAD

**Issue by logological** [GregThib/ttrss-tumblr-gdpr#12]
Following a TTRSS update a few days ago, the plugin doesn't seem to work anymore.  The following error is displayed when updating feeds from the terminal:

```
PHP Fatal error:  Call to undefined function _debug_suppress() in /home/psy/public_html/ttrss/plugins.local/tumblr_gdpr/init.php on line 44
```

**Comment by logological** [comment]
Oh, never mind—it seems I was using an outdated version (1.2 instead of 2.1).  Upgrading has made the error go away.

**Comment by GregThib** [comment]
Nice :)
