### ISSUE TITLE
Suggestion: Add keywords to this repository.

### ISSUE THREAD

**Issue by maurice-schleussinger** [GregThib/ttrss-tumblr-gdpr#13]
First: Thanks for creating this plugin. Tumblr should really fix this.

I would suggest you add some keywords and/or at least the string "Tiny Tiny RSS" somewhere in the readme. I searched for Tiny Tiny RSS Tumblr in Google/Github and didn't find this at first because you only use the abbreviation.

**Comment by GregThib** [comment]
OH! You're right. I changed the topic and the README.md file.
Please, tell me if you think about another place.

(Have I the ability to add keywords on a repo ? I don't know where in such case. Let me know.)

**Comment by maurice-schleussinger** [comment]
That should do it. 🙂 

Keywords can be added online: 
<img width="1437" alt="pasted_image_23_01_19__10_20" src="https://user-images.githubusercontent.com/1615089/51596126-8397d800-1ef8-11e9-8a50-70b3a5844922.png">

**Comment by GregThib** [comment]
Oh, that is what "Topics" mean here… Done that!
