### ISSUE TITLE
Setting the custom CURLOPT_PROGRESSFUNCTION leads to CURLE_ABORTED_BY_CALLBACK 

### ISSUE THREAD

**Issue by VincentKueszter** [GregThib/ttrss-tumblr-gdpr#2]
Edit: I just noticed [https://github.com/GregThib/ttrss-tumblr-gdpr/issues/1#issuecomment-391085918](virgoparnas comment), the issue lies in MAX_DOWNLOAD_FILE_SIZE being undefined.

Hello,

the plugin didn't work out of the box for me.
After some tinkering, I noticed `curl_exec` returns false, with error code `42 (CURLE_ABORTED_BY_CALLBACK)`.
The only place this error could have happened was the `CURLOPT_PROGRESSFUNCTION`.
After commenting those three lines out ([76-78](https://github.com/GregThib/ttrss-tumblr-gdpr/blob/93d724b42c98121f77de281e57df43ae15fe8dd4/tumblr_gdpr/init.php#L76) in 93d724b) the plugin worked flawlessly (thanks for your hard work by the way!).

Since I am unsure how relevant testing for MAX_DOWNLOAD_FILE_SIZE is, I did not make it a pull request.
Do you know why this might have happened there?

**Comment by GregThib** [comment]
It appears that this error is due to an older version of TTRSS. See conversation [here](https://discourse.tt-rss.org/t/change-on-tumblr-rss-feeds-not-working/1158/52).

I keep open this issue and PR until I will adapt the code for (not too) outdated versions of TT-RSS.

**Comment by VincentKueszter** [comment]
Ah, of course! That explains it, thanks.
