### ISSUE TITLE
Unable to activate the plugin :(

### ISSUE THREAD

**Issue by vincegre** [GregThib/ttrss-tumblr-gdpr#5]
I'm trying to use your plugin on my tt-rss install but got no success. I downloaded the zip from github, unzipped it in my plugins.local directory but I'm unable to see the plugin in plugin list of tt-RSS to activate the plugin :(
Missing something here ?

Thanks

**Comment by VincentKueszter** [comment]
Did you create a subfolder for the plugin in plugins.local?
`plugins.local/tumblr_gdpr/init.php`

**Comment by vincegre** [comment]
yep it's exactly what I have but it still doesn't show up in plugins list of TT-RSS on web :(
needs some special rights on dir/file ?

**Comment by logological** [comment]
Same problem here.  The plugin was working fine when I first installed it back on 22 May.  Then I pulled in some updates (currently at f625092beb2fbfed405722bb574bcb6f485aa021) and now it doesn't work and no longer appears in my list of plugins in the Tiny Tiny RSS front end.

**Comment by logological** [comment]
Oh, I hadn't noticed that in Commit 93d724b42c98121f77de281e57df43ae15fe8dd4 you changed the name of the installation directory.  When I rename my existing directory from `af_tumblr_gdpr` to `tumblr_gdpr` the plugin reappears in the list.  I've re-enabled it now and hopefully it will work.

**Comment by vincegre** [comment]
> Oh, I hadn't noticed that in Commit 93d724b you changed the name of the installation directory. When I rename my existing directory from af_tumblr_gdpr to tumblr_gdpr the plugin reappears in the list. I've re-enabled it now and hopefully it will work.

Excellent point it made it ;) Perhaps the readme should include a note about using that specific folder name ??
