### ISSUE TITLE
Can't subscribe to feeds with plugin enabled

### ISSUE THREAD

**Issue by logological** [GregThib/ttrss-tumblr-gdpr#7]
When the ttrss-tumblr-gdpr plugin is enabled, I can't subscribe to any feeds (not just Tumblr ones).

Reproducibility: Always

Steps to reproduce:
1. Enable the ttrss-tumblr-gdpr plugin.
2. If your browser is configured to use Tiny Tiny RSS to open RSS feeds, then use it to visit any RSS feed.  Otherwise, craft a URL that makes Tiny Tiny RSS subscribe to a feed with a known URL (e.g., `http://www.example.com/ttrss/public.php?op=subscribe&feed_url=https%3A%2F%2Fbibliobemused.blogspot.com%2Ffeeds%2Fposts%2Fdefault`, but substitute your own domain and path to your Tiny Tiny RSS installation) and point your browser to it.

Observed behaviour:
1. The following error message appears:

> Could not subscribe to https://bibliobemused.blogspot.com/feeds/posts/default.
> Can't download the Feed URL.

Expected behaviour:
1. Tiny Tiny RSS should have subscribed me to the feed (or given me an "already subscribed" error if I am already subscribed to the feed).

**Comment by GregThib** [comment]
Hmmm, weird.
What are your versions of PHP and Curl installed ?
Do you have errors logged ? (like ones logged by tt-rss via config.php, or system pane in prefs, or apache/php side ?)

I cannot reproduce your issue.
As possible, give me more information and I'll try to find out where is the problem.

**Comment by logological** [comment]
I am running:

PHP 5.6.33
Curl 7.52.1
Tiny Tiny RSS v17.12 (f530224)
tumblr_gdpr 1.10

Tiny Tiny RSS is running on a Raspbian system.  I don't think the problem is on the client side; the problem is reproducible when accessing Tiny Tiny RSS through SeaMonkey 2.49.2, Firefox 60.0.1, and Chromium 66.0.3359.170.

Tiny Tiny RSS is configured to log errors to the system pane.  No errors appear in the log when I try to subscribe to a feed with the plugin enabled.

**Comment by GregThib** [comment]
Hi,

My apologies because I didn't see the problem you had.
I have fixed this, and tagged this new version 1.2.
Could you try it, check the patch is working well and if it is, close this issue ?

Thanks a lot.

**Comment by logological** [comment]
Yep, seems to be working now.  Thanks!
